# Generated by Django 4.1.2 on 2022-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='negative_marking_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
